### ISSUE TITLE
alertmanagers not being configured in prometheus.yml

### ISSUE THREAD

**Issue by madeinoz67** [ernestas-poskus/ansible-prometheus#37]
I had a problem where the alert notification wasn't working, alerts we're showing up in prometheus, but not making it to alertmanager and hence the notification receivers were not working.

I've added the following manually to prometheus.yml and alert notifications is now working via alertmanager and receivers.

```
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "localhost:9093"
```

I've had a look at the role variables and can't seem to see any related variables to set these.
