### ISSUE TITLE
alert receiver config formatting 

### ISSUE THREAD

**Issue by madeinoz67** [ernestas-poskus/ansible-prometheus#38]
in my playbook I have the following var set to define my receivers

```
prometheus_alert_manager_config_receivers:
  - name: 'default'
    slack_configs:
      - channel: '#operations'
        send_resolved: true
    email_configs:
      - to: 'user@emailaddress'
        send_resolved: true
```

when the playbook is run the config gets generated like this:

```
receivers:
-   email_configs:
    -   send_resolved: true
        to: user@emailaddress
    name: default
    slack_configs:
    -   channel: '#operations'
        send_resolved: true
```
