### ISSUE TITLE
notifications Ranging over all received Alerts

### ISSUE THREAD

**Issue by madeinoz67** [ernestas-poskus/ansible-prometheus#41]
Ok I'm not clear on how to define the slack receiver text and description as per https://prometheus.io/docs/alerting/notification_examples/#ranging-over-all-received-alerts for this role:

My config:
```
  - name: 'default'
    slack_configs:
      - channel: '#alerts'
        username: 'Alert-Manager'
        title: "[[ range $Alerts ]][[ $Annotations.summary ]]\n[[ end ]]"
        text: "[[ range $Alerts ]][[ $Annotations.description ]]\n[[ end ]]"
        send_resolved: true
``` 

What is being generated in prometheus.yml
```
    slack_configs:
    -   channel: '#alerts'
        send_resolved: true
        text: '[[ range $Alerts ]][[ $Annotations.description ]]

            [[ end ]]'
        title: '[[ range $Alerts ]][[ $Annotations.summary ]]

            [[ end ]]'
```

first it appears that the [[ ]] are not being converted to { } for the receiver fields

secondly I'm not sure if the I'm required to put the $ in front or leave as per the above link i.e. .Alerts and .Annotations.decription etc

**Comment by madeinoz67** [comment]
I have tested manually by directly editing alertmanager.yml and is working as per below config, so can confirm that braces [[]] are not converting to {{}} correctly

```
   slack_configs:
    -   channel: '#alerts'
        send_resolved: true
        text: "{{ .CommonAnnotations.description }}\n"
        title: "{{ .CommonAnnotations.summary }}\n"
        username: Alert-Manager
```

The range is not working as per previous link however is not an issue with this role so i will investigate solution further.
